timezone: America/Chicago
encoding: utf-8
host: 192.168.81.129
port: 3000
sass:
    sass_dir: _sass
    style: compressed
kramdown:
    input: GFM
    syntax_highlighter: rouge
paginate: 10
paginate_path: "/blog/page:num/"
